; PlatformIO Project Configuration File

; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting

[platformio]

; ============================================================
; SENSOR NODE
; ESP32 + sensors + edge model + LoRa #1
; ============================================================

[env:esp32dev]

platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    bblanchon/ArduinoJson @ ^7.3.0
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/Adafruit SHT31 Library
    adafruit/Adafruit MPU6050

build_src_filter =
    +<main.cpp>
    +<lora.cpp>
    +<sensors.cpp>
    +<sensor_packet.cpp>
    +<purbavas_edge_model.cpp>


; ============================================================
; GATEWAY
; ESP32 + LoRa #2
; Receives 12-byte packets and converts them to JSON
; ============================================================

[env:gateway]

platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    bblanchon/ArduinoJson @ ^7.3.0
    sandeepmistry/LoRa @ ^0.8.0

build_src_filter =
    +<gateway.cpp>